// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskList.Components.Domain.Infra.Data;

#nullable disable

namespace TaskList.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241008144210_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskList.Components.Domain.Main.Entities.TaskEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Id")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("tasklist", (string)null);
                });

            modelBuilder.Entity("TaskList.Components.Domain.Main.Entities.TaskEntity", b =>
                {
                    b.OwnsMany("TaskList.Components.Domain.Main.ValueObjects.Task", "Tasks", b1 =>
                        {
                            b1.Property<string>("TaskEntityUserId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Deadline")
                                .HasColumnType("DATETIME")
                                .HasColumnName("deadline");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("VARCHAR(255)")
                                .HasColumnName("description");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("DATETIME")
                                .HasColumnName("started_at");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("title");

                            b1.HasKey("TaskEntityUserId", "Id");

                            b1.ToTable("Task");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityUserId");
                        });

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
